/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ardiuno;

import meter.MeterView;
import com.fazecast.jSerialComm.SerialPort;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import controller.DBController;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.net.MalformedURLException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.Properties;
import java.util.Random;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.activation.DataHandler;
import javax.activation.DataSource;
import javax.activation.FileDataSource;
import javax.imageio.ImageIO;
import javax.mail.BodyPart;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Multipart;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import meter.CalReading;
import model.Meter;
import model.RepairModel;
import model.Transformer;
import org.jfree.chart.ChartPanel;
 

/**
 *
 * @author SANJAYA
 */
public class Controller extends javax.swing.JFrame {

    public static SerialPort Port;
    private SerialPort[] serialPorts;
    private MeterView meter1;
    private MeterView meter2;
    private MeterView meter3;
    
    TimeSeriesDemo1 demo;
    JFileChooser jFileChooser;

    /**
     * Creates new form Controller
     */
    public Controller() {
        initComponents();
        setting();
        meter();
        getconnection();
        this.pack();
        setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        comboShowTranformermeter = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        criticalTem = new javax.swing.JLabel();
        criticalwindtemp = new javax.swing.JLabel();
        criticaloilLevel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        comboViewRepair = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        comboRepairAddid = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtrepairDescription = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnSaveRepair = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        grapsIdTrasnfomer = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtIdTransformer = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtModelTransformer = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtLocationTransformer = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDescriptionTransformer = new javax.swing.JTextField();
        btnCancelTransformer = new javax.swing.JButton();
        btnSaveTransformer = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtIdMeter = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtMaxValeMeter = new javax.swing.JTextField();
        btnCancelMeter = new javax.swing.JButton();
        btnSaveMeter = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        comboIdTransformer = new javax.swing.JComboBox();
        comboTypeMeter = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        connectButton = new javax.swing.JButton();
        selectCOM = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTabbedPane1FocusGained(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 262, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 252, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        comboShowTranformermeter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboShowTranformermeterActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Transformer ID");

        criticalTem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        criticalTem.setText("Critical Value : ");

        criticalwindtemp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        criticalwindtemp.setText("Critical Value : ");

        criticaloilLevel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        criticaloilLevel.setText("Critical Value : ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(55, 55, 55)
                .addComponent(comboShowTranformermeter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(criticalTem)
                .addGap(195, 195, 195)
                .addComponent(criticalwindtemp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(criticaloilLevel)
                .addGap(60, 60, 60))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboShowTranformermeter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(34, 34, 34)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(criticalTem)
                        .addComponent(criticalwindtemp))
                    .addComponent(criticaloilLevel))
                .addGap(0, 160, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Home", jPanel5);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("ID Transformer");

        comboViewRepair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboViewRepairActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "View", "Send"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGap(31, 31, 31)
                        .addComponent(comboViewRepair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboViewRepair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("View Repair", jPanel9);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("ID Transformer");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Description");

        txtrepairDescription.setRows(5);
        jScrollPane1.setViewportView(txtrepairDescription);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Images");

        jButton1.setText("Select Image");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnSaveRepair.setText("Save");
        btnSaveRepair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveRepairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(155, 155, 155)
                        .addComponent(comboRepairAddid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnSaveRepair)
                        .addGroup(jPanel12Layout.createSequentialGroup()
                            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13)
                                .addComponent(jLabel5))
                            .addGap(112, 112, 112)
                            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton1)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboRepairAddid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel5))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jButton1)))
                .addGap(115, 115, 115)
                .addComponent(btnSaveRepair)
                .addContainerGap(196, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Add Repair", jPanel12);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        jTabbedPane1.addTab("Maintenence", jPanel1);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 509, Short.MAX_VALUE)
        );

        grapsIdTrasnfomer.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "100", "224", "33333" }));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Tranformer ID :");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Meter ID");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(79, 79, 79)
                        .addComponent(grapsIdTrasnfomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addGap(55, 55, 55)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(204, 204, 204))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grapsIdTrasnfomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Graphs", jPanel2);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("ID Transformer   :");

        txtIdTransformer.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIdTransformerFocusGained(evt);
            }
        });
        txtIdTransformer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdTransformerActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Model                 :");

        txtModelTransformer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelTransformerActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Location             :");

        txtLocationTransformer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLocationTransformerActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Description         :");

        txtDescriptionTransformer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescriptionTransformerActionPerformed(evt);
            }
        });

        btnCancelTransformer.setText("Cancel");
        btnCancelTransformer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelTransformerActionPerformed(evt);
            }
        });

        btnSaveTransformer.setText("Save");
        btnSaveTransformer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveTransformerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCancelTransformer)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel10Layout.createSequentialGroup()
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9))
                            .addGap(59, 59, 59)
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtLocationTransformer, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                                .addComponent(txtDescriptionTransformer)))
                        .addGroup(jPanel10Layout.createSequentialGroup()
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7))
                            .addGap(58, 58, 58)
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtModelTransformer, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                                .addComponent(txtIdTransformer)))))
                .addGap(18, 18, 18)
                .addComponent(btnSaveTransformer)
                .addContainerGap(171, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtIdTransformer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtModelTransformer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(txtLocationTransformer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtDescriptionTransformer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelTransformer)
                    .addComponent(btnSaveTransformer))
                .addGap(53, 53, 53))
        );

        jTabbedPane1.addTab("Add Transformer", jPanel10);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("ID Meter             :");

        txtIdMeter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdMeterActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Type                   :");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Max Value            :");

        txtMaxValeMeter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaxValeMeterActionPerformed(evt);
            }
        });
        txtMaxValeMeter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMaxValeMeterKeyPressed(evt);
            }
        });

        btnCancelMeter.setText("Cancel");
        btnCancelMeter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelMeterActionPerformed(evt);
            }
        });

        btnSaveMeter.setText("Save");
        btnSaveMeter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveMeterActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("ID Transformer   :");

        comboIdTransformer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboIdTransformerActionPerformed(evt);
            }
        });
        comboIdTransformer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                comboIdTransformerKeyPressed(evt);
            }
        });

        comboTypeMeter.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Wind", "Oil Temp", "Oil Level" }));
        comboTypeMeter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                comboTypeMeterKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCancelMeter)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaxValeMeter, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel14))
                                .addGap(58, 58, 58)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboIdTransformer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIdMeter, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboTypeMeter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(53, 53, 53)))
                .addGap(18, 18, 18)
                .addComponent(btnSaveMeter)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtIdMeter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(comboIdTransformer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(comboTypeMeter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(txtMaxValeMeter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 254, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelMeter)
                    .addComponent(btnSaveMeter))
                .addGap(53, 53, 53))
        );

        jTabbedPane1.addTab("Add Meter", jPanel11);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("GRID SUBSTATION MANAGEMENT SYSTEM");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(221, 221, 221))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));
        jPanel4.setPreferredSize(new java.awt.Dimension(30, 34));

        connectButton.setText("Connect");
        connectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectButtonActionPerformed(evt);
            }
        });

        selectCOM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectCOMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(307, 307, 307)
                .addComponent(selectCOM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(connectButton)
                .addGap(31, 31, 31))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(connectButton)
                    .addComponent(selectCOM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 832, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jTabbedPane1)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selectCOMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectCOMActionPerformed

    }//GEN-LAST:event_selectCOMActionPerformed

    private void connectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectButtonActionPerformed
        if (connectButton.getText().equals("Connect")) {
            Port = SerialPort.getCommPort(serialPorts[selectCOM.getSelectedIndex()].getSystemPortName());
            System.out.println(selectCOM.getSelectedIndex());
            Port.setComPortTimeouts(SerialPort.TIMEOUT_SCANNER, 0, 0);
            if (Port.openPort()) {
                System.out.println("port open :" + Port.isOpen());
                connectButton.setText("Disconnet");
                selectCOM.setEnabled(false);

            }
            Thread thread = new Thread() {
                public void run() {
                    Scanner scanner = new Scanner(Port.getInputStream());
                    Random random = new Random();
                    int r = random.nextInt(30);
                    Calendar saveTime = new GregorianCalendar();
                    Calendar nowTime = null;
                    CalReading calReading = new CalReading();
                    while (scanner.hasNextLine()) {
                        try {
                            String a = scanner.nextLine();
                            int kk = calReading.getValue(a);
                            meter1.setVal(kk);
                            nowTime = new GregorianCalendar();
                            if ((kk > 50) || ((nowTime.getTimeInMillis() - saveTime.getTimeInMillis()) >= 300000)) {
                                DBController.saveMeterReading(kk);
                            }
                        } catch (Exception e) {
                            System.out.println(e);
                        }
                    }
                    scanner.close();
                }
            };
            thread.start();
        } else {
            System.out.println("close port :" + Port.closePort());
            connectButton.setText("Connect");
            selectCOM.setEnabled(true);

        }
    }//GEN-LAST:event_connectButtonActionPerformed

    private void jTabbedPane1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedPane1FocusGained

    }//GEN-LAST:event_jTabbedPane1FocusGained

    private void comboIdTransformerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboIdTransformerActionPerformed
        
    }//GEN-LAST:event_comboIdTransformerActionPerformed

    private void btnSaveMeterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveMeterActionPerformed
        Meter meter = new Meter();
        try {
            meter.setIdMeter(Integer.parseInt(txtIdMeter.getText()));
            meter.setIdTransformer(Integer.parseInt(comboIdTransformer.getSelectedItem().toString()));
            meter.setMaxValue(Integer.parseInt(txtMaxValeMeter.getText()));
            meter.setType(comboTypeMeter.getSelectedItem().toString());
            try {
                int res = DBController.saveMeterDetails(meter);
                if (res > 0) {
                    JOptionPane.showMessageDialog(this, "Added Success");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error Input\n" + ex.getMessage().split("\\(")[0]);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Error Input\ntry integer\n" + ex.getMessage());
        }
    }//GEN-LAST:event_btnSaveMeterActionPerformed

    private void btnCancelMeterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelMeterActionPerformed
        txtIdMeter.setText("");
        txtMaxValeMeter.setText("");
    }//GEN-LAST:event_btnCancelMeterActionPerformed

    private void txtMaxValeMeterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaxValeMeterActionPerformed
        btnSaveMeter.requestFocus();
    }//GEN-LAST:event_txtMaxValeMeterActionPerformed

    private void txtIdMeterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdMeterActionPerformed
                comboIdTransformer.requestFocus();        
    }//GEN-LAST:event_txtIdMeterActionPerformed

    private void btnSaveTransformerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveTransformerActionPerformed
        Transformer transformer = new Transformer();
        try {
            transformer.setIdTransformer(Integer.parseInt(txtIdTransformer.getText()));
            transformer.setModel(txtModelTransformer.getText());
            transformer.setLocation(txtLocationTransformer.getText());
            transformer.setDescription(txtDescriptionTransformer.getText());
            try {
                int res = DBController.saveTransFormer(transformer);
                if (res > 0) {
                    JOptionPane.showMessageDialog(this, "Added Success");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error Input\n" + ex.getMessage());
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Error Input\ntry integer\n" + ex.getMessage());
        }
        initRun();
        clearAddTransformer();
    }//GEN-LAST:event_btnSaveTransformerActionPerformed

    private void btnCancelTransformerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelTransformerActionPerformed
                clearAddTransformer();
    }//GEN-LAST:event_btnCancelTransformerActionPerformed

    private void txtDescriptionTransformerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescriptionTransformerActionPerformed
        btnSaveTransformer.requestFocus();
    }//GEN-LAST:event_txtDescriptionTransformerActionPerformed

    private void txtLocationTransformerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLocationTransformerActionPerformed
        txtDescriptionTransformer.requestFocus();
    }//GEN-LAST:event_txtLocationTransformerActionPerformed

    private void txtModelTransformerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelTransformerActionPerformed
        txtLocationTransformer.requestFocus();
    }//GEN-LAST:event_txtModelTransformerActionPerformed

    private void txtIdTransformerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdTransformerActionPerformed
        txtModelTransformer.requestFocus();
    }//GEN-LAST:event_txtIdTransformerActionPerformed

    private void txtIdTransformerFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdTransformerFocusGained

    }//GEN-LAST:event_txtIdTransformerFocusGained

    private void comboShowTranformermeterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboShowTranformermeterActionPerformed
        try {
            ResultSet resultSet=DBController.getMeterMaxValue(comboShowTranformermeter.getSelectedItem().toString());
            while (resultSet.next()) {
                if("wind".equals(resultSet.getString(1))){
                    criticalwindtemp.setText("Critical Value: "+resultSet.getString(2));
                } else  if("Oil Temp".equals(resultSet.getString(1))){
                    criticalTem.setText("Critical Value: "+resultSet.getString(2));
                } else if("Oil Level".equals(resultSet.getString(1))){
                    criticaloilLevel.setText("Critical Value: "+resultSet.getString(2));
                }
            }
        } catch (SQLException ex) {
            
        }catch(NullPointerException ex){
            
        }
    }//GEN-LAST:event_comboShowTranformermeterActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jFileChooser = new JFileChooser();
        FileFilter filter=new FileNameExtensionFilter("Image files", ImageIO.getReaderFileSuffixes());
        jFileChooser.addChoosableFileFilter(filter);
        jFileChooser.setAcceptAllFileFilterUsed(false);
        jFileChooser.setMultiSelectionEnabled(true);
        jFileChooser.showOpenDialog(this);
        File[] file=jFileChooser.getSelectedFiles();        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSaveRepairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveRepairActionPerformed
        try {
            RepairModel repairModel = new RepairModel();
            repairModel.setIdTransfomer(Integer.parseInt(comboRepairAddid.getSelectedItem().toString()));
            repairModel.setDescription(txtrepairDescription.getText());
            repairModel.setFiles(jFileChooser.getSelectedFiles());
            try {
                DBController.SaveRepair(repairModel);
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(this, "Error Input\n" + ex.getMessage());
            }
        } catch (SQLException ex) {
            Logger.getLogger(Controller.class.getName()).log(Level.SEVERE, null, ex);
        }
        viewRepair();
    }//GEN-LAST:event_btnSaveRepairActionPerformed

    private void comboViewRepairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboViewRepairActionPerformed
        viewRepair();        
        
    }//GEN-LAST:event_comboViewRepairActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try {
            System.out.println(jTable1.getValueAt(jTable1.getSelectedRow(), 0));
            List<Image> images=DBController.getImage((int) jTable1.getValueAt(jTable1.getSelectedRow(), 0));
            try {
                createPDF(images);
            } catch (DocumentException ex) {
                Logger.getLogger(Controller.class.getName()).log(Level.SEVERE, null, ex);
            } catch (MalformedURLException ex) {
                Logger.getLogger(Controller.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error Input\n" + ex.getMessage().split("\\(")[0]);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error Input\n" + ex.getMessage().split("\\(")[0]);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void comboIdTransformerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboIdTransformerKeyPressed
        if(KeyEvent.VK_ENTER==evt.getKeyCode()){
            comboTypeMeter.requestFocus();
        }
    }//GEN-LAST:event_comboIdTransformerKeyPressed

    private void comboTypeMeterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboTypeMeterKeyPressed
        if(KeyEvent.VK_ENTER==evt.getKeyCode()){
            txtMaxValeMeter.requestFocus();
        }
    }//GEN-LAST:event_comboTypeMeterKeyPressed

    private void txtMaxValeMeterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaxValeMeterKeyPressed
        if(KeyEvent.VK_ENTER==evt.getKeyCode()){
            btnSaveMeter.requestFocus();
        }
    }//GEN-LAST:event_txtMaxValeMeterKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Controller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Controller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Controller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Controller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Controller();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelMeter;
    private javax.swing.JButton btnCancelTransformer;
    private javax.swing.JButton btnSaveMeter;
    private javax.swing.JButton btnSaveRepair;
    private javax.swing.JButton btnSaveTransformer;
    private javax.swing.JComboBox comboIdTransformer;
    private javax.swing.JComboBox comboRepairAddid;
    private javax.swing.JComboBox comboShowTranformermeter;
    private javax.swing.JComboBox comboTypeMeter;
    private javax.swing.JComboBox comboViewRepair;
    private javax.swing.JButton connectButton;
    private javax.swing.JLabel criticalTem;
    private javax.swing.JLabel criticaloilLevel;
    private javax.swing.JLabel criticalwindtemp;
    private javax.swing.JComboBox grapsIdTrasnfomer;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox selectCOM;
    private javax.swing.JTextField txtDescriptionTransformer;
    private javax.swing.JTextField txtIdMeter;
    private javax.swing.JTextField txtIdTransformer;
    private javax.swing.JTextField txtLocationTransformer;
    private javax.swing.JTextField txtMaxValeMeter;
    private javax.swing.JTextField txtModelTransformer;
    private javax.swing.JTextArea txtrepairDescription;
    // End of variables declaration//GEN-END:variables

    private void getconnection() {
        txtrepairDescription.setColumns(10);
        serialPorts = SerialPort.getCommPorts();
        if (serialPorts.length == 0) {
            connectButton.setVisible(false);
        } else {
            connectButton.setVisible(true);
        }
        for (SerialPort serialPort : serialPorts) {
            selectCOM.addItem(serialPort.getDescriptivePortName());
        } 
        initRun();
    }

    private void meter() {
        meter1 = new MeterView(0, 150, 10, 50D, 100D, 150D, "temperature");
        meter2 = new MeterView(0, 150, 10, 50D, 100D, 150D, "wind");
        meter3 = new MeterView(0, 150, 10, 50D, 100D, 150D, "Oil Level");
        ChartPanel cp1 = meter1.buildDialPlot();
        cp1.setSize(225, 225);

        jPanel6.add(cp1);
        ChartPanel cp2 = meter2.buildDialPlot();
        cp2.setSize(225, 225);
        jPanel7.add(cp2);
        ChartPanel cp3 = meter3.buildDialPlot();
        cp3.setSize(225, 225);
        jPanel8.add(cp3);
        
        demo = new TimeSeriesDemo1("Time Series Demo 1");
        ChartPanel cp=demo.getChartPanel();
        cp.setSize(700, 500);
        jPanel13.add(cp);
    }

    private void setting() {
        setLocationRelativeTo(null);
        ImageIcon fillingIcon = new ImageIcon(getClass().getClassLoader().getResource("img/ceb.png"));
        java.awt.Image im = fillingIcon.getImage().getScaledInstance(200, 200, 1);        
        this.setIconImage(im);        
    }
    private void initRun(){
        comboShowTranformermeter.removeAllItems();
        comboRepairAddid.removeAllItems();
        comboViewRepair.removeAllItems();
        grapsIdTrasnfomer.removeAllItems();
        comboIdTransformer.removeAllItems();
        try {
            ResultSet resultSet=DBController.getTransformerId();
            while(resultSet.next()){
                comboShowTranformermeter.addItem(resultSet.getInt("idTransformer"));
                comboRepairAddid.addItem(resultSet.getInt("idTransformer"));
                comboViewRepair.addItem(resultSet.getInt("idTransformer"));
                grapsIdTrasnfomer.addItem(resultSet.getInt("idTransformer"));
                comboIdTransformer.addItem(resultSet.getInt("idTransformer"));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error Restart\n" + ex.getMessage().split("\\(")[0]);
        }
    }

    private void viewRepair() {
        try {
            ResultSet rst=DBController.getRepair(comboViewRepair.getSelectedItem().toString());
            DefaultTableModel dtm=(DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);
            while(rst.next()){
                Object[] rowData={rst.getInt("idRepair"),rst.getString("time"),rst.getString("Description")};
                dtm.addRow(rowData);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error Input\n" + ex.getMessage().split("\\(")[0]);
        }
    }

    private void createPDF(List<Image> images) throws DocumentException, MalformedURLException, IOException {
        FileOutputStream pdfFileout = null;
        try {
            File file = new File("itext.pdf");
            pdfFileout = new FileOutputStream(file);
            Document doc = new Document();
            try {
                PdfWriter.getInstance(doc, pdfFileout);
            } catch (DocumentException ex) {
                Logger.getLogger(Controller.class.getName()).log(Level.SEVERE, null, ex);
            }
            doc.addAuthor("QuicklyJava.com");
            doc.addTitle("This is title");
            doc.open();
            Paragraph para1 = new Paragraph();
            para1.add("Date :"+(String) jTable1.getValueAt(jTable1.getSelectedRow(), 1));
            Paragraph para2 = new Paragraph();
            para2.add((String) jTable1.getValueAt(jTable1.getSelectedRow(), 2));
            doc.add(para1);
            doc.add(para2);
            //Adding an online image
            
            for (Image image : images) {                
                doc.add(com.itextpdf.text.Image.getInstance(image,null));
            }
            //adding a local image and aligned RIGHT
            
            
            doc.close();
            pdfFileout.close();
            System.out.println("Success!");
            String email=JOptionPane.showInputDialog(this, "Email");
            sendEmail(email,file);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Controller.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                pdfFileout.close();
            } catch (IOException ex) {
                Logger.getLogger(Controller.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private void sendEmail(String email, File file)  {
        final String username = "chethiya92@gmail.com";
        final String password = "922581460";
        Properties props = new Properties();
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.port", "587");
        Session session = Session.getInstance(props,
                new javax.mail.Authenticator() {
                    protected PasswordAuthentication getPasswordAuthentication() {
                        return new PasswordAuthentication(username, password);
                    }
                });
        Message message = new MimeMessage(session);
        DataSource source=null;
        BodyPart messageBodyPart = new MimeBodyPart();
        Multipart multipart = new MimeMultipart();
        
                
        try {
            message.setFrom(new InternetAddress("chethiya92@gmail.com"));
            message.setRecipients(Message.RecipientType.TO,
                    InternetAddress.parse(email));
            message.setSubject("Testing Subject");
            message.setText("Dear Mail Crawler,"
                    + "\n\n No spam to my email, please!");
            
            source = new FileDataSource(file);
            messageBodyPart.setDataHandler(new DataHandler(source));
            multipart.addBodyPart(messageBodyPart);
            messageBodyPart.setFileName(file.getName());
            message.setContent(multipart);
            Transport.send(message);
            System.out.println("Done");   
        } catch (MessagingException ex) {
            JOptionPane.showMessageDialog(this, "Error \n" + ex.getMessage().split("\\(")[0]);
        }        
                             
    }

    private void clearAddTransformer() {
        txtIdTransformer.setText("");
        txtModelTransformer.setText("");
        txtLocationTransformer.setText("");
        txtDescriptionTransformer.setText("");
    }
    
}
